### PR TITLE
Also exclude whitelisted children

### PR DESCRIPTION
**Pull request by sunesimonsen**
This will ignore excluded items at expansion time.

### CODE REVIEW

**Comment by papandreou** [comment]
Did you change your mind about this solution? :thinking:

**Comment by sunesimonsen** [comment]
No I closed in favor of your solution. Feel free to merge it.

**Comment by sunesimonsen** [comment]
I'll give you access to Github and npm when I'm at a computer

**Comment by papandreou** [comment]
Okay, will do :)

**Pull request closed without merging**
